
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: Jenkins-Zero-To-Hero
  namespace: fluxcd
spec:
  interval: 30s
  path: ./java-maven-sonar-argocd-helm-k8s
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: Jenkins-Zero-To-Hero
