---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: Jenkins-Zero-To-Hero
  namespace: fluxcd
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/hackerboypk/Jenkins-Zero-To-Hero.git
